import { NodeResult, Params, Stream } from "../engine/types";
import { CalcRow } from "./calcsheets";

/**
 * Design calculation recipes for the high-strength wastewater units.
 *
 * Same contract as calcsheets.ts: `expr` carries ${key} placeholders that the
 * Excel writer turns into live cell references, `formula` is the symbolic form,
 * and `theory` explains where the relationship comes from for the learning
 * export.
 */

const n = (p: Params, k: string, d = 0): number => {
  const v = p[k];
  return typeof v === "number" && Number.isFinite(v) ? v : d;
};

type Builder = (r: NodeResult, p: Params) => CalcRow[];

function duty(r: NodeResult): CalcRow[] {
  return [
    { section: "Duty" },
    {
      key: "Qin", no: "1", item: "Inlet flow", symbol: "Q_in", unit: "m³/h",
      val: r.inlet.flow, input: true,
      note: "From the water balance.",
      theory:
        "Every sizing calculation starts from the hydraulic duty. Get this wrong and nothing downstream can be right, which is why the water balance is solved before any equipment is sized.",
    },
  ];
}

export const ADVANCED_BUILDERS: Record<string, Builder> = {
  /* ------------------------------------------------------ pH adjustment */
  phadjust: (r, p) => [
    ...duty(r),
    { section: "Where the reagent demand comes from" },
    { key: "pH0", no: "2", item: "Inlet pH", symbol: "pH_0", unit: "-", val: r.inlet.pH, input: true },
    { key: "pHt", no: "3", item: "Target pH", symbol: "pH_t", unit: "-", val: n(p, "targetPH", 11), input: true,
      note: "11.0 before stripping; 6.5–7.0 before a membrane.",
      theory: "pH does not measure how much acid or base is present, only the activity of the hydrogen ion. Two waters at the same pH can need doses a hundredfold apart, which is why the dose is calculated from the species present and confirmed by titration, never from the pH difference." },
    { key: "T", no: "4", item: "Temperature", symbol: "T", unit: "°C", val: r.inlet.T, input: true,
      note: "Enters through the ammonia dissociation constant." },
    { key: "HCO3", no: "5", item: "Bicarbonate", symbol: "C_HCO3", unit: "mg/L", val: r.inlet.c.HCO3, input: true },
    { key: "alk", no: "6", item: "Alkalinity as CaCO₃", symbol: "Alk", unit: "mg/L", expr: "${HCO3}/61.02*50",
      formula: "Alk = C_HCO3 / 61.02 × 50",
      theory: "Alkalinity is conventionally reported as calcium carbonate so that different bases can be added together. One milliequivalent per litre is 50 mg/L as CaCO₃, which is the bridge between the two." },
    { key: "alkeq", no: "7", item: "Carbonate demand", symbol: "eq_C", unit: "meq/L", expr: "${alk}/50",
      formula: "eq_C = Alk / 50" },
    { key: "NH4", no: "8", item: "Ammonium", symbol: "C_NH4", unit: "mg/L", val: r.inlet.c.NH4, input: true },
    { key: "pKa", no: "9", item: "Ammonia dissociation constant", symbol: "pKa", unit: "-",
      expr: "0.09018+2729.92/(${T}+273.15)", formula: "pKa = 0.09018 + 2729.92 / (T + 273.15)",
      note: "9.25 at 25 °C; 9.10 at 30 °C.",
      theory: "Emerson et al. (1975). The constant falls as temperature rises, which is why a warm water has more of its ammonia in the free, strippable form at the same pH — and why tropical sites strip ammonia more cheaply than temperate ones." },
    { key: "f0", no: "10", item: "Free NH₃ at inlet pH", symbol: "f_0", unit: "-",
      expr: "1/(1+10^(${pKa}-${pH0}))", formula: "f = 1 / (1 + 10^(pKa − pH))" },
    { key: "f1", no: "11", item: "Free NH₃ at target pH", symbol: "f_1", unit: "-",
      expr: "1/(1+10^(${pKa}-${pHt}))", formula: "f = 1 / (1 + 10^(pKa − pH))" },
    { key: "nheq", no: "12", item: "Ammonium demand", symbol: "eq_N", unit: "meq/L",
      expr: "${NH4}/18.039*MAX(${f1}-${f0},0)", formula: "eq_N = (C_NH4 / 18.04) × (f_1 − f_0)",
      note: "Usually the dominant term on a leachate.",
      theory: "Every ammonium ion that becomes free ammonia has to give up a proton, and that proton consumes one hydroxide. At several thousand mg/L of ammoniacal nitrogen this term is an order of magnitude larger than the carbonate system, which is the single most common reason a caustic dosing system is under-ordered." },
    { section: "Reagent" },
    { key: "eqt", no: "13", item: "Total equivalent demand", symbol: "eq", unit: "meq/L",
      expr: "${alkeq}+${nheq}", formula: "eq = eq_C + eq_N" },
    { key: "exc", no: "14", item: "Dosing excess", symbol: "x", unit: "%", val: n(p, "excessPct", 15), input: true,
      note: "10–20 % for control lag." },
    { key: "keq", no: "15", item: "Equivalents dosed", symbol: "E", unit: "keq/h",
      expr: "${eqt}*(1+${exc}/100)*${Qin}/1000", formula: "E = eq × (1 + x/100) × Q_in / 1000" },
    { key: "naoh", no: "16", item: "Caustic soda demand", symbol: "M_NaOH", unit: "kg/h",
      expr: "${keq}*39.997", formula: "M = E × MW_NaOH",
      theory: "Sodium hydroxide carries one hydroxide per formula unit, so one kilo-equivalent is one kilomole is 40 kg. Hydrated lime carries two, so the same duty needs 37 kg of Ca(OH)₂ — cheaper per equivalent, but it adds calcium and leaves sludge." },
    { key: "tpd", no: "17", item: "Daily reagent", symbol: "M_d", unit: "t/d",
      expr: "${naoh}*24/1000", formula: "M_d = M × 24 / 1000",
      note: "The number that gets quoted to a client, and usually the largest single operating cost." },
    { section: "Tank" },
    { key: "hrt", no: "18", item: "Reaction time", symbol: "t", unit: "min", val: n(p, "hrtMin", 20), input: true,
      note: "15–30 min. The chemistry is instant; the time is for mixing." },
    { key: "vol", no: "19", item: "Tank volume", symbol: "V", unit: "m³",
      expr: "${Qin}*${hrt}/60", formula: "V = Q_in × t / 60" },
    { key: "wm3", no: "20", item: "Mixing intensity", symbol: "P/V", unit: "W/m³", val: n(p, "mixWkW", 40), input: true },
    { key: "mix", no: "21", item: "Mixer power", symbol: "P", unit: "kW",
      expr: "${vol}*${wm3}/1000", formula: "P = V × (P/V) / 1000" },
  ],

  /* --------------------------------------------------- ammonia stripping */
  nh3strip: (r, p) => [
    ...duty(r),
    { section: "How much of the ammonia can leave" },
    { key: "pH", no: "2", item: "Operating pH", symbol: "pH", unit: "-", val: r.inlet.pH, input: true,
      note: "Below 10.5 the removal collapses while the blower power does not." },
    { key: "T", no: "3", item: "Temperature", symbol: "T", unit: "°C", val: r.inlet.T, input: true },
    { key: "pKa", no: "4", item: "Dissociation constant", symbol: "pKa", unit: "-",
      expr: "0.09018+2729.92/(${T}+273.15)", formula: "pKa = 0.09018 + 2729.92 / (T + 273.15)" },
    { key: "f", no: "5", item: "Free ammonia fraction", symbol: "f", unit: "-",
      expr: "1/(1+10^(${pKa}-${pH}))", formula: "f = 1 / (1 + 10^(pKa − pH))",
      note: "0.98 at pH 11; 0.35 at pH 9; 0.006 at pH 7.",
      theory: "Only the uncharged NH₃ molecule can cross into the gas phase. The ammonium ion is charged and stays in the water however much air is blown past it. This one fraction is why the pH is raised to 11 before the tower and dropped again after it." },
    { section: "Contact" },
    { key: "GL", no: "6", item: "Air-to-water ratio", symbol: "G/L", unit: "m³/m³", val: n(p, "airRatio", 3000), input: true,
      note: "2000–4000. CCEPC designs leachate towers at 3000.",
      theory: "Ammonia partitions between water and air according to Henry's law, so enough air has to pass to carry the ammonia away without approaching equilibrium. Below about 1500 the air saturates and the removal falls; above 4000 the extra air buys very little for a proportional increase in blower power." },
    { key: "cont", no: "7", item: "Contact efficiency", symbol: "η", unit: "-",
      expr: "1-EXP(-${GL}/1350)", formula: "η = 1 − exp(−(G/L) / K)",
      note: "K = 1350, fitted so that 3000 m³/m³ reproduces the CCEPC design removal." },
    { key: "R", no: "8", item: "Ammonia removal", symbol: "R", unit: "-",
      expr: "${f}*${cont}", formula: "R = f × η",
      theory: "The product of two independent limits: how much of the ammonia is in a form that can leave, and how much of that the tower actually contacts. Neither alone predicts the result." },
    { section: "Nitrogen balance" },
    { key: "NH4", no: "9", item: "Inlet ammonium", symbol: "C_NH4", unit: "mg/L", val: r.inlet.c.NH4, input: true },
    { key: "NH4N", no: "10", item: "As nitrogen", symbol: "C_N", unit: "mgN/L",
      expr: "${NH4}*14.007/18.039", formula: "C_N = C_NH4 × MW_N / MW_NH4" },
    { key: "TN", no: "11", item: "Inlet total nitrogen", symbol: "TN", unit: "mg/L", val: r.inlet.c.TN, input: true },
    { key: "orgN", no: "12", item: "Organic nitrogen", symbol: "N_org", unit: "mg/L",
      expr: "MAX(${TN}-${NH4N},0)", formula: "N_org = TN − C_N",
      note: "Cannot be stripped at any air ratio. It is the floor on what this unit can do.",
      theory: "Stripping removes a dissolved gas. Nitrogen bound into an organic molecule is not a gas and does not leave, which is why a leachate with a large organic-nitrogen fraction cannot reach a low total nitrogen by stripping however hard the tower is driven." },
    { key: "Nrem", no: "13", item: "Nitrogen stripped", symbol: "M_N", unit: "kgN/h",
      expr: "${Qin}*${NH4N}*${R}/1000", formula: "M_N = Q_in × C_N × R / 1000" },
    { section: "Tower geometry" },
    { key: "air", no: "14", item: "Air flow", symbol: "Q_air", unit: "m³/h",
      expr: "${Qin}*${GL}", formula: "Q_air = Q_in × (G/L)" },
    { key: "LL", no: "15", item: "Liquid loading limit", symbol: "L_A", unit: "m³/m².h", val: n(p, "liquidLoading", 25), input: true },
    { key: "vg", no: "16", item: "Gas velocity limit", symbol: "v_g", unit: "m/s", val: n(p, "maxGasVel", 2.0), input: true,
      note: "Packed towers flood above roughly 2–3 m/s." },
    { key: "AL", no: "17", item: "Area from liquid", symbol: "A_L", unit: "m²",
      expr: "${Qin}/${LL}", formula: "A_L = Q_in / L_A" },
    { key: "AG", no: "18", item: "Area from gas", symbol: "A_G", unit: "m²",
      expr: "${air}/3600/${vg}", formula: "A_G = Q_air / 3600 / v_g" },
    { key: "A", no: "19", item: "Governing area", symbol: "A", unit: "m²",
      expr: "MAX(${AL},${AG})", formula: "A = max(A_L, A_G)",
      note: "At a high air ratio the gas always governs.",
      theory: "At 3000 m³ of air per m³ of water the gas volumetric flow is three thousand times the liquid. Sizing the tower from the water alone gives a diameter several times too small, and it floods on the day it starts. This is the most common error in a stripping tower design." },
    { key: "D", no: "20", item: "Tower diameter", symbol: "D", unit: "m",
      expr: "SQRT(4*${A}/PI())", formula: "D = √(4A / π)" },
    { key: "H", no: "21", item: "Packing height", symbol: "H", unit: "m", val: n(p, "packingHeightM", 8), input: true,
      note: "6–12 m." },
    { section: "Power" },
    { key: "dp", no: "22", item: "Packing pressure drop", symbol: "Δp", unit: "Pa", val: n(p, "packingDPa", 1500), input: true },
    { key: "eb", no: "23", item: "Blower efficiency", symbol: "η_b", unit: "-", val: n(p, "blowerEff", 0.7), input: true },
    { key: "Pb", no: "24", item: "Blower power", symbol: "P_b", unit: "kW",
      expr: "${air}/3600*${dp}/${eb}/1000", formula: "P_b = (Q_air / 3600) × Δp / η_b / 1000",
      theory: "Fan power is volumetric flow times pressure rise divided by efficiency. Multiplied by a very large air flow, a modest packing pressure drop becomes the dominant running cost of the unit." },
    { section: "Acid scrubber" },
    { key: "sc", no: "25", item: "Scrubber capture", symbol: "η_s", unit: "%", val: n(p, "scrubberEff", 97), input: true },
    { key: "h2so4", no: "26", item: "Sulphuric acid demand", symbol: "M_acid", unit: "kg/h",
      expr: "${Nrem}*${sc}/100/14.007/2*98.079", formula: "M_acid = (M_N × η_s) / MW_N / 2 × MW_H2SO4",
      note: "≈ 3.5 kg H₂SO₄ per kg N.",
      theory: "2 NH₃ + H₂SO₄ → (NH₄)₂SO₄. Two moles of ammonia are neutralised by one mole of sulphuric acid, so the acid demand follows directly from the nitrogen captured." },
    { key: "as", no: "27", item: "Ammonium sulphate produced", symbol: "M_AS", unit: "kg/h",
      expr: "${Nrem}*${sc}/100/14.007/2*132.14", formula: "M_AS = (M_N × η_s) / MW_N / 2 × MW_(NH4)2SO4",
      note: "≈ 4.7 kg per kg N. A fertiliser — but only if there is an offtake." },
    { key: "astpd", no: "28", item: "Fertiliser per day", symbol: "M_AS,d", unit: "t/d",
      expr: "${as}*24/1000", formula: "M_AS,d = M_AS × 24 / 1000" },
  ],

  /* ------------------------------------------------------------- MBR */
  mbr: (r, p) => [
    ...duty(r),
    { section: "Reactor" },
    { key: "hrt", no: "2", item: "Total HRT", symbol: "t", unit: "h", val: n(p, "hrtH", 24), input: true },
    { key: "vol", no: "3", item: "Reactor volume", symbol: "V", unit: "m³",
      expr: "${Qin}*${hrt}", formula: "V = Q_in × t" },
    { key: "mlss", no: "4", item: "MLSS", symbol: "X", unit: "mg/L", val: n(p, "mlss", 10000), input: true,
      note: "8000–12000. Above 12000 the oxygen transfer collapses.",
      theory: "Replacing the clarifier with a membrane removes the settling limit on biomass concentration, so the same treatment fits in roughly a third of the tank. That is the entire economic case for an MBR." },
    { key: "BOD", no: "5", item: "Inlet BOD", symbol: "C_BOD", unit: "mg/L", val: r.inlet.c.BOD, input: true },
    { key: "Rb", no: "6", item: "BOD removal", symbol: "R_BOD", unit: "%", val: n(p, "bodRemoval", 95), input: true },
    { key: "Lb", no: "7", item: "BOD load removed", symbol: "L", unit: "kg/h",
      expr: "${Qin}*${BOD}*${Rb}/100/1000", formula: "L = Q_in × C_BOD × R_BOD / 100 / 1000" },
    { key: "fm", no: "8", item: "F/M ratio", symbol: "F/M", unit: "kgBOD/kgMLSS.d",
      expr: "${Lb}*24/(${vol}*${mlss}/1000)", formula: "F/M = 24L / (V × X / 1000)",
      note: "0.05–0.15 for an MBR." },
    { section: "Oxygen" },
    { key: "NH4", no: "9", item: "Inlet ammonium", symbol: "C_NH4", unit: "mg/L", val: r.inlet.c.NH4, input: true },
    { key: "Rn", no: "10", item: "Ammonia removal", symbol: "R_N", unit: "%", val: n(p, "nh4Removal", 90), input: true },
    { key: "Ln", no: "11", item: "Nitrogen nitrified", symbol: "L_N", unit: "kgN/h",
      expr: "${Qin}*${NH4}*14.007/18.039*${Rn}/100/1000", formula: "L_N = Q_in × C_NH4 × (MW_N/MW_NH4) × R_N / 100 / 1000" },
    { key: "o2", no: "12", item: "Oxygen demand", symbol: "M_O2", unit: "kgO₂/h",
      expr: "${Lb}*1.2+${Ln}*4.57", formula: "M_O2 = 1.2L + 4.57 L_N",
      theory: "1.2 kg of oxygen per kg of BOD covers respiration and endogenous decay. The 4.57 comes from the nitrification stoichiometry: two moles of oxygen per mole of ammonia oxidised to nitrate, which works out at 4.57 kg per kg of nitrogen exactly." },
    { key: "ae", no: "13", item: "Aeration efficiency", symbol: "AE", unit: "kgO₂/kWh", val: n(p, "aeUp", 1.2), input: true,
      note: "1.2 at high MLSS and salinity, against 2.5–3 in clean municipal sludge." },
    { key: "Pa", no: "14", item: "Process aeration power", symbol: "P_a", unit: "kW",
      expr: "${o2}/${ae}", formula: "P_a = M_O2 / AE" },
    { section: "Alkalinity — the check that gets forgotten" },
    { key: "HCO3", no: "15", item: "Inlet bicarbonate", symbol: "C_HCO3", unit: "mg/L", val: r.inlet.c.HCO3, input: true },
    { key: "alk", no: "16", item: "Alkalinity available", symbol: "Alk", unit: "mg/L as CaCO₃",
      expr: "${HCO3}/61.02*50", formula: "Alk = C_HCO3 / 61.02 × 50" },
    { key: "alkn", no: "17", item: "Alkalinity consumed", symbol: "Alk_c", unit: "mg/L as CaCO₃",
      expr: "${Qin}*0+${NH4}*14.007/18.039*${Rn}/100*7.14", formula: "Alk_c = C_N × R_N/100 × 7.14",
      note: "7.14 mg as CaCO₃ per mg of N nitrified.",
      theory: "Nitrification releases two protons per ammonium oxidised, which destroy alkalinity. On a high-ammonia water the alkalinity runs out before the ammonia does, the pH falls, and nitrification stalls — a failure that looks like a biology problem and is really a chemistry one." },
    { key: "alkl", no: "18", item: "Alkalinity remaining", symbol: "Alk_r", unit: "mg/L as CaCO₃",
      expr: "${alk}-${alkn}", formula: "Alk_r = Alk − Alk_c",
      note: "Below about 100 the pH will crash. Dose alkalinity or lower the ammonia target." },
    { section: "Membrane" },
    { key: "flux", no: "19", item: "Net flux", symbol: "J", unit: "LMH", val: n(p, "flux", 12), input: true,
      note: "15–25 municipal, 8–15 leachate. Not the clean-water figure.",
      theory: "Flux in mixed liquor is limited by the cake layer that builds on the membrane, not by the membrane itself. A module rated at 60 LMH on clean water delivers a quarter of that in an MBR, and quoting the clean-water figure is how membrane areas end up specified at a third of what is needed." },
    { key: "Qp", no: "20", item: "Permeate flow", symbol: "Q_p", unit: "m³/h",
      val: (r.outlets.out as Stream)?.flow ?? r.inlet.flow, input: true },
    { key: "area", no: "21", item: "Membrane area", symbol: "A", unit: "m²",
      expr: "${Qp}*1000/${flux}", formula: "A = Q_p × 1000 / J" },
    { key: "sa", no: "22", item: "Scouring air rate", symbol: "q_s", unit: "Nm³/m².h", val: n(p, "scourAir", 0.35), input: true },
    { key: "Qs", no: "23", item: "Scouring air flow", symbol: "Q_s", unit: "Nm³/h",
      expr: "${area}*${sa}", formula: "Q_s = A × q_s" },
    { key: "Ps", no: "24", item: "Scouring blower power", symbol: "P_s", unit: "kW",
      expr: "${Qs}/3600*6000/0.65/1000", formula: "P_s = (Q_s/3600) × Δp / η / 1000",
      note: "Runs continuously, whether or not there is load.",
      theory: "Air is swept along the membrane surface to stop solids settling on it. It performs no treatment at all, and on a typical MBR it is a third to a half of total plant power. It is the reason an MBR costs more to run than the activated sludge plant it replaced." },
    { key: "share", no: "25", item: "Scouring share of power", symbol: "-", unit: "%",
      expr: "100*${Ps}/(${Pa}+${Ps})", formula: "P_s / (P_a + P_s) × 100" },
  ],

  /* ------------------------------------------------------- anaerobic */
  anaerobic: (r, p) => [
    ...duty(r),
    { section: "Volume — loading governs, not retention time" },
    { key: "COD", no: "2", item: "Inlet COD", symbol: "C_COD", unit: "mg/L", val: r.inlet.c.COD, input: true },
    { key: "Lcod", no: "3", item: "COD load", symbol: "L", unit: "kg/d",
      expr: "${Qin}*24*${COD}/1000", formula: "L = Q_in × 24 × C_COD / 1000" },
    { key: "olr", no: "4", item: "Organic loading rate", symbol: "B_v", unit: "kgCOD/m³.d", val: n(p, "olr", 8), input: true,
      note: "UASB 4–12, EGSB 10–25.",
      theory: "The granular biomass can only turn over so much substrate per unit volume per day. Exceed it and volatile fatty acids accumulate faster than the methanogens consume them, the pH falls, and the reactor sours — a failure that takes months to recover from." },
    { key: "Vo", no: "5", item: "Volume from loading", symbol: "V_B", unit: "m³",
      expr: "${Lcod}/${olr}", formula: "V_B = L / B_v" },
    { key: "hrt", no: "6", item: "Nominal HRT", symbol: "t", unit: "h", val: n(p, "hrtH", 24), input: true },
    { key: "Vh", no: "7", item: "Volume from HRT", symbol: "V_t", unit: "m³",
      expr: "${Qin}*${hrt}", formula: "V_t = Q_in × t" },
    { key: "V", no: "8", item: "Governing volume", symbol: "V", unit: "m³",
      expr: "MAX(${Vo},${Vh})", formula: "V = max(V_B, V_t)",
      note: "On strong wastewater the loading always governs." },
    { key: "vup", no: "9", item: "Upflow velocity", symbol: "v", unit: "m/h", val: n(p, "upflowVel", 1.0), input: true,
      note: "0.5–1.5 UASB. Too high and the granules wash out." },
    { key: "A", no: "10", item: "Cross-sectional area", symbol: "A", unit: "m²",
      expr: "${Qin}/${vup}", formula: "A = Q_in / v" },
    { key: "H", no: "11", item: "Reactor height", symbol: "H", unit: "m",
      expr: "${V}/${A}", formula: "H = V / A" },
    { section: "Gas" },
    { key: "Rc", no: "12", item: "COD removal", symbol: "R", unit: "%", val: n(p, "codRemoval", 75), input: true },
    { key: "Lr", no: "13", item: "COD removed", symbol: "L_r", unit: "kg/h",
      expr: "${Qin}*${COD}*${Rc}/100/1000", formula: "L_r = Q_in × C_COD × R / 100 / 1000" },
    { key: "yld", no: "14", item: "Methane yield", symbol: "Y_CH4", unit: "Nm³/kgCOD", val: n(p, "ch4Yield", 0.30), input: true,
      note: "0.35 theoretical, 0.28–0.32 collected.",
      theory: "Complete anaerobic oxidation of one kg of COD yields 0.35 Nm³ of methane at standard conditions, from the stoichiometry of methane combustion run backwards. The rest of the shortfall goes to biomass and to methane that stays dissolved and leaves with the effluent." },
    { key: "ch4", no: "15", item: "Methane produced", symbol: "Q_CH4", unit: "Nm³/h",
      expr: "${Lr}*${yld}", formula: "Q_CH4 = L_r × Y_CH4" },
    { key: "fr", no: "16", item: "Methane in biogas", symbol: "y", unit: "%", val: n(p, "ch4Fraction", 65), input: true },
    { key: "gas", no: "17", item: "Biogas flow", symbol: "Q_g", unit: "Nm³/h",
      expr: "${ch4}/(${fr}/100)", formula: "Q_g = Q_CH4 / y" },
    { key: "kw", no: "18", item: "Recoverable energy", symbol: "P_th", unit: "kW",
      expr: "${ch4}*9.97", formula: "P_th = Q_CH4 × LHV",
      note: "Lower heating value of methane, 9.97 kWh/Nm³. Only a credit if something on site can burn it." },
    { section: "Sulphate check" },
    { key: "SO4", no: "19", item: "Inlet sulphate", symbol: "C_SO4", unit: "mg/L", val: r.inlet.c.SO4, input: true },
    { key: "ratio", no: "20", item: "COD : sulphate", symbol: "-", unit: "-",
      expr: "${COD}/MAX(${SO4},1)", formula: "COD / C_SO4",
      note: "Below 10, sulphate reducers outcompete the methanogens and you get H₂S instead of methane." },
  ],

  /* ------------------------------------------------------------ DTRO */
  dtro: (r, p) => [
    ...duty(r),
    { section: "Recovery and flows" },
    { key: "Y", no: "2", item: "Overall recovery", symbol: "Y", unit: "%", val: n(p, "recovery", 85), input: true,
      note: "75–80 % single stage; 85 % over two." },
    { key: "st", no: "3", item: "Stages in series", symbol: "-", unit: "-", val: n(p, "stages", 2), input: true },
    { key: "Qp", no: "4", item: "Permeate flow", symbol: "Q_p", unit: "m³/h",
      expr: "${Qin}*${Y}/100", formula: "Q_p = Q_in × Y" },
    { key: "Qc", no: "5", item: "Concentrate flow", symbol: "Q_c", unit: "m³/h",
      expr: "${Qin}-${Qp}", formula: "Q_c = Q_in − Q_p" },
    { key: "CF", no: "6", item: "Concentration factor", symbol: "CF", unit: "-",
      expr: "1/(1-${Y}/100)", formula: "CF = 1 / (1 − Y)",
      theory: "Everything rejected leaves in a smaller flow, so its concentration rises by exactly this factor. At 85 % recovery that is 6.7 times, and it is what sets both the scaling risk and the osmotic pressure the pump has to overcome." },
    { key: "LM", no: "7", item: "Log-mean factor", symbol: "LM", unit: "-",
      expr: "LN(1/(1-${Y}/100))/(${Y}/100)", formula: "LM = ln(1/(1−Y)) / Y",
      note: "2.23 at 85 % recovery.",
      theory: "The concentration rises continuously along the module, so the membrane does not see the feed concentration — it sees something between feed and concentrate. The logarithmic mean is the standard approximation, and it is why a membrane with 99.3 % local rejection delivers only 98.5 % across the system." },
    { section: "Pressure" },
    { key: "TDSf", no: "8", item: "Feed TDS", symbol: "C_f", unit: "mg/L", val: r.inlet.c.TDS, input: true },
    { key: "osf", no: "9", item: "Feed osmotic pressure", symbol: "π_f", unit: "bar",
      expr: "0.78*${TDSf}/1000", formula: "π = 0.78 × TDS / 1000",
      theory: "Van 't Hoff: osmotic pressure is proportional to the molar concentration of dissolved species. For a typical mixed salt at ambient temperature it works out at about 0.78 bar per 1000 mg/L. A membrane cannot produce any water at all below this pressure, so it is the floor under everything else." },
    { key: "TDSc", no: "10", item: "Concentrate TDS", symbol: "C_c", unit: "mg/L",
      val: (r.outlets.concentrate as Stream)?.c.TDS ?? 0, input: true },
    { key: "osc", no: "11", item: "Concentrate osmotic pressure", symbol: "π_c", unit: "bar",
      expr: "0.78*${TDSc}/1000", formula: "π = 0.78 × TDS / 1000" },
    { key: "P", no: "12", item: "Feed pressure", symbol: "p", unit: "bar",
      expr: "(${osf}+${osc})/2+8+3*${st}", formula: "p = (π_f + π_c)/2 + NDP + Δp_module",
      note: "60–120 bar on leachate. Check against the module rating." },
    { key: "eff", no: "13", item: "Pump efficiency", symbol: "η", unit: "-", val: n(p, "pumpEff", 0.75), input: true },
    { key: "kw", no: "14", item: "Pump power", symbol: "P_kW", unit: "kW",
      expr: "1000*9.81*(${Qin}/3600)*(${P}*10.2)/${eff}/1000",
      formula: "P = ρ g Q H / η",
      note: "10.2 m of head per bar." },
    { key: "sec", no: "15", item: "Specific energy", symbol: "SEC", unit: "kWh/m³",
      expr: "${kw}/${Qp}", formula: "SEC = P / Q_p",
      note: "6–15 on leachate, against 0.5–1 for brackish RO." },
    { section: "Membrane area" },
    { key: "J", no: "16", item: "Flux", symbol: "J", unit: "LMH", val: n(p, "flux", 18), input: true,
      note: "18 LMH is the CCEPC leachate design figure." },
    { key: "A", no: "17", item: "Membrane area", symbol: "A", unit: "m²",
      expr: "${Qp}*1000/${J}", formula: "A = Q_p × 1000 / J" },
    { key: "am", no: "18", item: "Area per module", symbol: "a", unit: "m²", val: n(p, "moduleArea", 9), input: true },
    { key: "nm", no: "19", item: "Modules", symbol: "N", unit: "-",
      expr: "ROUNDUP(${A}/${am},0)", formula: "N = ⌈A / a⌉" },
  ],

  /* ------------------------------------------------------------- AOP */
  aop: (r, p) => [
    ...duty(r),
    { section: "Oxidant demand — set by load, not by flow" },
    { key: "COD", no: "2", item: "Inlet COD", symbol: "C_in", unit: "mg/L", val: r.inlet.c.COD, input: true,
      note: "This is the number that decides the cost of the unit." },
    { key: "R", no: "3", item: "COD removal", symbol: "R", unit: "%", val: n(p, "codRemoval", 60), input: true },
    { key: "Lr", no: "4", item: "COD destroyed", symbol: "L", unit: "kg/h",
      expr: "${Qin}*${COD}*${R}/100/1000", formula: "L = Q_in × C_in × R / 100 / 1000",
      theory: "Hydroxyl radicals are consumed stoichiometrically by the molecules they attack, so the oxidant demand follows the mass of organic matter destroyed — not the flow. This is why the same unit placed after a membrane instead of before it can cost a hundredth as much to run while producing the same effluent." },
    { key: "sp", no: "5", item: "Ozone per COD", symbol: "y", unit: "kgO₃/kgCOD", val: n(p, "o3PerCod", 2.5), input: true,
      note: "2.5 is the CCEPC design basis. Confirm on the real water." },
    { key: "o3", no: "6", item: "Ozone demand", symbol: "M_O3", unit: "kg/h",
      expr: "${Lr}*${sp}", formula: "M_O3 = L × y" },
    { key: "o3d", no: "7", item: "Ozone per day", symbol: "M_d", unit: "kg/d",
      expr: "${o3}*24", formula: "M_d = M_O3 × 24",
      note: "Generators are quoted in kg/d, so this is the size on the purchase order." },
    { section: "Power" },
    { key: "ge", no: "8", item: "Generation energy", symbol: "e", unit: "kWh/kgO₃", val: n(p, "o3EnergyKWhKg", 10), input: true,
      note: "8–12 from oxygen feed; roughly double from air." },
    { key: "P", no: "9", item: "Generator power", symbol: "P", unit: "kW",
      expr: "${o3}*${ge}", formula: "P = M_O3 × e" },
    { key: "sec", no: "10", item: "Specific energy", symbol: "SEC", unit: "kWh/m³",
      expr: "${P}/${Qin}", formula: "SEC = P / Q_in",
      note: "0.5–2 as a polish; 50–200 if applied to raw leachate. Same unit, same chemistry, different position." },
    { key: "ox", no: "11", item: "Oxygen consumption", symbol: "M_O2", unit: "kg/h",
      expr: "${o3}*12", formula: "M_O2 = M_O3 × 12",
      note: "Only 6–10 % of the feed oxygen becomes ozone; the rest is returned or vented." },
    { section: "Contact" },
    { key: "t", no: "12", item: "Contact time", symbol: "t", unit: "min", val: n(p, "contactMin", 30), input: true },
    { key: "V", no: "13", item: "Contact volume", symbol: "V", unit: "m³",
      expr: "${Qin}*${t}/60", formula: "V = Q_in × t / 60" },
  ],

  /* ------------------------------------------------------------- BAF */
  baf: (r, p) => [
    ...duty(r),
    { section: "Bed" },
    { key: "vf", no: "2", item: "Filtration rate", symbol: "v", unit: "m/h", val: n(p, "filtrationRate", 4), input: true,
      note: "2–6 m/h." },
    { key: "A", no: "3", item: "Filter area", symbol: "A", unit: "m²",
      expr: "${Qin}/${vf}", formula: "A = Q_in / v" },
    { key: "d", no: "4", item: "Media depth", symbol: "h", unit: "m", val: n(p, "mediaDepthM", 3), input: true },
    { key: "V", no: "5", item: "Media volume", symbol: "V", unit: "m³",
      expr: "${A}*${d}", formula: "V = A × h" },
    { section: "Load" },
    { key: "BOD", no: "6", item: "Inlet BOD", symbol: "C_BOD", unit: "mg/L", val: r.inlet.c.BOD, input: true },
    { key: "Rb", no: "7", item: "BOD removal", symbol: "R", unit: "%", val: n(p, "bodRemoval", 90), input: true },
    { key: "L", no: "8", item: "BOD load removed", symbol: "L", unit: "kg/d",
      expr: "${Qin}*24*${BOD}*${Rb}/100/1000", formula: "L = Q_in × 24 × C_BOD × R / 100 / 1000" },
    { key: "Bv", no: "9", item: "Volumetric load", symbol: "B_v", unit: "kgBOD/m³.d",
      expr: "${L}/${V}", formula: "B_v = L / V",
      note: "1.5–4 for carbon removal, 0.3–1 for nitrification.",
      theory: "The hydraulic rate sets the area; the volumetric load decides whether the attached biofilm can actually process what arrives. Exceed the second and the bed blinds however generous the first appears." },
    { section: "Air and backwash" },
    { key: "gl", no: "10", item: "Air ratio", symbol: "G/L", unit: "m³/m³", val: n(p, "airRatio", 12), input: true },
    { key: "Qa", no: "11", item: "Process air", symbol: "Q_air", unit: "m³/h",
      expr: "${Qin}*${gl}", formula: "Q_air = Q_in × (G/L)" },
    { key: "Pb", no: "12", item: "Blower power", symbol: "P", unit: "kW",
      expr: "${Qa}/3600*(${d}*9810+3000)/0.65/1000", formula: "P = (Q_air/3600) × (ρgh + Δp) / η / 1000" },
    { key: "bw", no: "13", item: "Backwash water", symbol: "b", unit: "%", val: n(p, "backwashPct", 5), input: true },
    { key: "Qbw", no: "14", item: "Backwash flow", symbol: "Q_bw", unit: "m³/h",
      expr: "${Qin}*${bw}/100", formula: "Q_bw = Q_in × b / 100",
      note: "Returned to the head of works, so it reduces net capacity by the same amount." },
  ],

  /* --------------------------------------------------- electro-oxidation */
  electroox: (r, p) => [
    ...duty(r),
    { section: "Load and energy" },
    { key: "COD", no: "2", item: "Inlet COD", symbol: "C_in", unit: "mg/L", val: r.inlet.c.COD, input: true },
    { key: "R", no: "3", item: "COD removal", symbol: "R", unit: "%", val: n(p, "codRemoval", 55), input: true },
    { key: "L", no: "4", item: "COD destroyed", symbol: "L", unit: "kg/h",
      expr: "${Qin}*${COD}*${R}/100/1000", formula: "L = Q_in × C_in × R / 100 / 1000" },
    { key: "se", no: "5", item: "Specific energy", symbol: "e", unit: "kWh/kgCOD", val: n(p, "specEnergy", 30), input: true,
      note: "20–40 on saline water; far more at low conductivity.",
      theory: "Charge has to be passed for every electron transferred, and the cell voltage needed to pass it depends on the solution resistance. A low-conductivity water therefore costs more energy for the same oxidation, which is why the process only makes sense on a saline stream." },
    { key: "P", no: "6", item: "Rectifier power", symbol: "P", unit: "kW",
      expr: "${L}*${se}", formula: "P = L × e" },
    { key: "sec", no: "7", item: "Specific energy per volume", symbol: "SEC", unit: "kWh/m³",
      expr: "${P}/${Qin}", formula: "SEC = P / Q_in" },
    { section: "Cell" },
    { key: "U", no: "8", item: "Cell voltage", symbol: "U", unit: "V", val: n(p, "cellVoltage", 6), input: true },
    { key: "I", no: "9", item: "Current", symbol: "I", unit: "A",
      expr: "${P}*1000/${U}", formula: "I = P / U" },
    { key: "j", no: "10", item: "Current density", symbol: "j", unit: "A/m²", val: n(p, "currentDensity", 300), input: true },
    { key: "Aa", no: "11", item: "Anode area", symbol: "A", unit: "m²",
      expr: "${I}/${j}", formula: "A = I / j" },
    { section: "Chloride check" },
    { key: "Cl", no: "12", item: "Chloride", symbol: "C_Cl", unit: "mg/L", val: r.inlet.c.Cl, input: true,
      note: "Above ~1500 mg/L the indirect chlorine route works; below it the energy climbs steeply and by-products still form." },
  ],

  /* ------------------------------------------------------ oil separation */
  oilsep: (r, p) => [
    ...duty(r),
    { section: "Area from the design droplet" },
    { key: "vr", no: "2", item: "Design rise rate", symbol: "v_r", unit: "m/h", val: n(p, "riseRateMh", 1.2), input: true,
      note: "Corresponds to the smallest droplet to be captured: 150 µm for API, 60 µm for CPI.",
      theory: "Stokes' law run upwards. The rise velocity goes with the square of the droplet diameter and with the density difference, so halving the design droplet size quadruples the area required. That single choice, made early and often unexamined, sets the size of the vessel." },
    { key: "A", no: "3", item: "Separator area", symbol: "A", unit: "m²",
      expr: "${Qin}/${vr}", formula: "A = Q_in / v_r" },
    { key: "t", no: "4", item: "Retention time", symbol: "t", unit: "min", val: n(p, "hrtMin", 30), input: true },
    { key: "V", no: "5", item: "Volume", symbol: "V", unit: "m³",
      expr: "${Qin}*${t}/60", formula: "V = Q_in × t / 60" },
    { section: "Oil balance" },
    { key: "Cin", no: "6", item: "Inlet oil", symbol: "C_oil", unit: "mg/L", val: r.inlet.c.Oil, input: true },
    { key: "R", no: "7", item: "Oil removal", symbol: "R", unit: "%", val: n(p, "oilRemoval", 90), input: true,
      note: "Of free and dispersed oil only. Emulsified oil passes untouched." },
    { key: "M", no: "8", item: "Oil recovered", symbol: "M", unit: "kg/h",
      expr: "${Qin}*${Cin}*${R}/100/1000", formula: "M = Q_in × C_oil × R / 100 / 1000" },
    { key: "Cout", no: "9", item: "Outlet oil", symbol: "C_out", unit: "mg/L",
      expr: "${Cin}*(1-${R}/100)", formula: "C_out = C_oil × (1 − R)",
      note: "20–100 mg/L is the realistic floor. A limit below that needs flotation as well." },
  ],
};
